# Generated by Django 6.0.6 on 2026-06-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_campus', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion_fisica', models.CharField(max_length=300)),
                ('provincia', models.CharField(max_length=100)),
                ('infraestructura_compartida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_corte', models.DateField()),
                ('total_cupos_aceptados', models.IntegerField(default=0)),
                ('registros_totales', models.IntegerField(default=0)),
                ('registros_validos', models.IntegerField(default=0)),
                ('registros_observados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consolidado académico',
                'verbose_name_plural': 'Consolidados académicos',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_parcial_1', models.FloatField(default=0.0)),
                ('calificacion_parcial_2', models.FloatField(default=0.0)),
                ('nota_final', models.FloatField(default=0.0)),
                ('porcentaje_asistencia', models.FloatField(default=0.0)),
                ('estado_de_aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Retirado', 'Retirado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=50)),
                ('observacion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Evaluación académica',
                'verbose_name_plural': 'Evaluaciones académicas',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDeDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_de_horas_cumplidas', models.FloatField(default=0.0)),
                ('entrega_oportuna_de_calificaciones', models.BooleanField(default=False)),
                ('porcentaje_de_aprobacion_paralelo', models.FloatField(default=0.0)),
                ('resultado_de_evaluacion_estudiantil', models.FloatField(default=0.0)),
                ('puntaje_final', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Evaluación de desempeño',
                'verbose_name_plural': 'Evaluaciones de desempeño',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('espacio_de_imparticion', models.CharField(max_length=200)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('numero_semana', models.IntegerField()),
                ('tipo_de_sesion', models.CharField(choices=[('Sincrónica', 'Sincrónica'), ('Asincrónica', 'Asincrónica'), ('Evaluación', 'Evaluación')], max_length=50)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_incidencia', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_incidencia', models.DateField()),
            ],
            options={
                'verbose_name': 'Incidencia académica',
                'verbose_name_plural': 'Incidencias académicas',
            },
        ),
        migrations.CreateModel(
            name='InformeGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_informe', models.CharField(max_length=100, unique=True)),
                ('tipo_de_informe', models.CharField(choices=[('Planificación', 'Planificación'), ('Avance', 'Avance'), ('Final', 'Final')], max_length=50)),
                ('estado_de_informe', models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('Aprobado', 'Aprobado')], default='Borrador', max_length=50)),
                ('fecha_de_emision', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Informe general',
                'verbose_name_plural': 'Informes generales',
            },
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_malla', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('area_de_conocimiento', models.CharField(max_length=200)),
                ('duracion_semanas', models.IntegerField()),
                ('version_de_malla', models.CharField(max_length=20)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('estado', models.CharField(choices=[('Diseño', 'Diseño'), ('Activa', 'Activa'), ('Histórica', 'Histórica'), ('Inactiva', 'Inactiva')], default='Diseño', max_length=50)),
                ('total_horas_nivelacion', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Malla curricular',
                'verbose_name_plural': 'Mallas curriculares',
            },
        ),
        migrations.CreateModel(
            name='MatriculaParalelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matrícula en paralelo',
                'verbose_name_plural': 'Matrículas en paralelos',
            },
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_paralelo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], max_length=50)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('capacidad_maxima', models.IntegerField(default=35)),
            ],
            options={
                'verbose_name': 'Paralelo',
                'verbose_name_plural': 'Paralelos',
            },
        ),
        migrations.CreateModel(
            name='PeriodoDeNivelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_periodo', models.CharField(max_length=50, unique=True)),
                ('anio', models.IntegerField()),
                ('periodo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('numero_periodo', models.IntegerField()),
                ('estado', models.CharField(choices=[('Planificación', 'Planificación'), ('En curso', 'En curso'), ('Evaluación', 'Evaluación'), ('Cerrado', 'Cerrado')], default='Planificación', max_length=50)),
            ],
            options={
                'verbose_name': 'Periodo de nivelación',
                'verbose_name_plural': 'Periodos de nivelación',
            },
        ),
        migrations.CreateModel(
            name='UnidadCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_unidad', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('area_de_conocimiento', models.JSONField(default=list)),
                ('horas_totales', models.FloatField()),
                ('horas_semanales', models.FloatField()),
                ('horas_sincronicas', models.FloatField()),
                ('horas_asincronicas', models.FloatField()),
                ('tipo_de_componente', models.CharField(choices=[('Teórico', 'Teórico'), ('Práctico', 'Práctico'), ('Tutorial', 'Tutorial')], max_length=50)),
                ('criterio_de_aprobacion', models.FloatField(default=7.0)),
                ('porcentaje_minimo_asistencia', models.FloatField(default=70.0)),
            ],
            options={
                'verbose_name': 'Unidad curricular',
                'verbose_name_plural': 'Unidades curriculares',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(max_length=20)),
                ('codigo_sniese', models.CharField(max_length=50, unique=True)),
                ('direccion_matriz', models.CharField(max_length=300)),
                ('identificador_visual', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_carrera', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('campo_de_conocimiento', models.CharField(max_length=200)),
                ('vigencia_sniese', models.DateField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academico.campus')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='CohorteDeMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_registro', models.CharField(max_length=50, unique=True)),
                ('nombre_cohorte', models.CharField(max_length=200)),
                ('fecha_de_cierre', models.DateField()),
                ('tipo_de_cohorte', models.CharField(choices=[('Primera matrícula', 'Primera matrícula'), ('Segunda matrícula', 'Segunda matrícula'), ('Exoneración', 'Exoneración')], max_length=50)),
                ('estado_de_cohorte', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=50)),
                ('total_primera_matricula', models.IntegerField(default=0)),
                ('total_segunda_matricula', models.IntegerField(default=0)),
                ('total_exonerados', models.IntegerField(default=0)),
                ('carrera_registrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='academico.carrera')),
            ],
            options={
                'verbose_name': 'Cohorte de matrícula',
                'verbose_name_plural': 'Cohortes de matrícula',
            },
        ),
    ]
