# Generated by Django 6.0.6 on 2026-06-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionacademica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_academicas', to='usuarios.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='evaluaciondedesempeno',
            name='docente_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_desempeno', to='usuarios.perfildocente'),
        ),
        migrations.AddField(
            model_name='incidenciaacademica',
            name='docente_implicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='usuarios.perfildocente'),
        ),
        migrations.AddField(
            model_name='incidenciaacademica',
            name='responsable_autorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_autorizadas', to='usuarios.perfiladministrativo'),
        ),
        migrations.AddField(
            model_name='informegeneral',
            name='cohortes',
            field=models.ManyToManyField(blank=True, related_name='informes', to='academico.cohortedematricula'),
        ),
        migrations.AddField(
            model_name='mallacurricular',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mallas_curriculares', to='academico.carrera'),
        ),
        migrations.AddField(
            model_name='matriculaparalelo',
            name='cohorte_de_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.cohortedematricula'),
        ),
        migrations.AddField(
            model_name='matriculaparalelo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_matriculados', to='usuarios.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paralelos', to='usuarios.perfildocente'),
        ),
        migrations.AddField(
            model_name='matriculaparalelo',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_matriculados', to='academico.paralelo'),
        ),
        migrations.AddField(
            model_name='horario',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.paralelo'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='academico.periododenivelacion'),
        ),
        migrations.AddField(
            model_name='informegeneral',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='academico.periododenivelacion'),
        ),
        migrations.AddField(
            model_name='evaluaciondedesempeno',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_desempeno', to='academico.periododenivelacion'),
        ),
        migrations.AddField(
            model_name='consolidadoacademico',
            name='periodo_academico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consolidado_academico', to='academico.periododenivelacion'),
        ),
        migrations.AddField(
            model_name='cohortedematricula',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes_de_matricula', to='academico.periododenivelacion'),
        ),
        migrations.AddField(
            model_name='unidadcurricular',
            name='malla_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_curriculares', to='academico.mallacurricular'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='unidad_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='academico.unidadcurricular'),
        ),
        migrations.AddField(
            model_name='evaluacionacademica',
            name='unidad_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_academicas', to='academico.unidadcurricular'),
        ),
        migrations.AddField(
            model_name='periododenivelacion',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_de_nivelacion', to='academico.universidad'),
        ),
        migrations.AddField(
            model_name='campus',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus', to='academico.universidad'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculaparalelo',
            unique_together={('estudiante', 'paralelo')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluaciondedesempeno',
            unique_together={('docente_responsable', 'periodo_de_nivelacion')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionacademica',
            unique_together={('estudiante', 'unidad_curricular')},
        ),
    ]
