# Generated by Django 6.0.5 on 2026-06-09 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('usuarios', '0002_alter_perfiladministrativo_identificador_administrativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='codigo_de_campus',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de campus'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='direccion_fisica',
            field=models.CharField(max_length=300, verbose_name='Dirección física'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='infraestructura_compartida',
            field=models.BooleanField(default=False, verbose_name='Infraestructura compartida'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='provincia',
            field=models.CharField(max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus', to='academico.universidad', verbose_name='Universidad registrada'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='campo_de_conocimiento',
            field=models.CharField(max_length=200, verbose_name='Campo de conocimiento'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academico.campus', verbose_name='Campus registrado'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='codigo_de_carrera',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de carrera'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='vigencia_sniese',
            field=models.DateField(verbose_name='Vigencia SNIESE'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='carrera_registrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='academico.carrera', verbose_name='Carrera registrada'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='codigo_de_registro',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de registro'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='estado_de_cohorte',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='fecha_de_cierre',
            field=models.DateField(verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='nombre_cohorte',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes_de_matricula', to='academico.periododenivelacion', verbose_name='Periodo de nivelación registrado'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='tipo_de_cohorte',
            field=models.CharField(choices=[('Primera matrícula', 'Primera matrícula'), ('Segunda matrícula', 'Segunda matrícula'), ('Exoneración', 'Exoneración')], max_length=50, verbose_name='Tipo de cohorte de matrícula'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='total_exonerados',
            field=models.IntegerField(default=0, verbose_name='Número de exonerados'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='total_primera_matricula',
            field=models.IntegerField(default=0, verbose_name='Número de primeras matrículas'),
        ),
        migrations.AlterField(
            model_name='cohortedematricula',
            name='total_segunda_matricula',
            field=models.IntegerField(default=0, verbose_name='Número de segundas matrículas'),
        ),
        migrations.AlterField(
            model_name='consolidadoacademico',
            name='fecha_de_corte',
            field=models.DateField(verbose_name='Fecha de corte'),
        ),
        migrations.AlterField(
            model_name='consolidadoacademico',
            name='periodo_academico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consolidado_academico', to='academico.periododenivelacion', verbose_name='Periodo de nivelación registrado'),
        ),
        migrations.AlterField(
            model_name='consolidadoacademico',
            name='registros_observados',
            field=models.IntegerField(default=0, verbose_name='Número de registros observados'),
        ),
        migrations.AlterField(
            model_name='consolidadoacademico',
            name='registros_totales',
            field=models.IntegerField(default=0, verbose_name='Número de registros'),
        ),
        migrations.AlterField(
            model_name='consolidadoacademico',
            name='registros_validos',
            field=models.IntegerField(default=0, verbose_name='Número de registros válidos'),
        ),
        migrations.AlterField(
            model_name='consolidadoacademico',
            name='total_cupos_aceptados',
            field=models.IntegerField(default=0, verbose_name='Número de cupos aceptados'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='calificacion_parcial_1',
            field=models.FloatField(default=0.0, verbose_name='Calificación primer parcial'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='calificacion_parcial_2',
            field=models.FloatField(default=0.0, verbose_name='Calificación segundo parcial'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='estado_de_aprobacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Retirado', 'Retirado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=50, verbose_name='Estado de aprobación'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_academicas', to='usuarios.perfilestudiante', verbose_name='Estudiante registrado'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='nota_final',
            field=models.FloatField(default=0.0, verbose_name='Calificación final'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='observacion',
            field=models.TextField(blank=True, default='', verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='porcentaje_asistencia',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de asistencia final'),
        ),
        migrations.AlterField(
            model_name='evaluacionacademica',
            name='unidad_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_academicas', to='academico.unidadcurricular', verbose_name='Unidad curricular registrada'),
        ),
        migrations.AlterField(
            model_name='evaluaciondedesempeno',
            name='docente_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_desempeno', to='usuarios.perfildocente', verbose_name='Docente responsable'),
        ),
        migrations.AlterField(
            model_name='evaluaciondedesempeno',
            name='entrega_oportuna_de_calificaciones',
            field=models.BooleanField(default=False, verbose_name='Entrega oportuna de calificaciones'),
        ),
        migrations.AlterField(
            model_name='evaluaciondedesempeno',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_desempeno', to='academico.periododenivelacion', verbose_name='Periodo de nivelación registrado'),
        ),
        migrations.AlterField(
            model_name='evaluaciondedesempeno',
            name='porcentaje_de_aprobacion_paralelo',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de aprobación de paralelo'),
        ),
        migrations.AlterField(
            model_name='evaluaciondedesempeno',
            name='porcentaje_de_horas_cumplidas',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de horas cumplidas'),
        ),
        migrations.AlterField(
            model_name='evaluaciondedesempeno',
            name='puntaje_final',
            field=models.FloatField(default=0.0, verbose_name='Puntaje final'),
        ),
        migrations.AlterField(
            model_name='evaluaciondedesempeno',
            name='resultado_de_evaluacion_estudiantil',
            field=models.FloatField(default=0.0, verbose_name='Resultado de evaluación estudiantil'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, verbose_name='Día de semana'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='espacio_de_imparticion',
            field=models.CharField(max_length=200, verbose_name='Espacio de impartición'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de finalización'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='modalidad',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='numero_semana',
            field=models.IntegerField(verbose_name='Número de semana'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.paralelo', verbose_name='Paralelo registrado'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tipo_de_sesion',
            field=models.CharField(choices=[('Sincrónica', 'Sincrónica'), ('Asincrónica', 'Asincrónica'), ('Evaluación', 'Evaluación')], max_length=50, verbose_name='Tipo de sesión'),
        ),
        migrations.AlterField(
            model_name='incidenciaacademica',
            name='codigo_incidencia',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de incidencia'),
        ),
        migrations.AlterField(
            model_name='incidenciaacademica',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='incidenciaacademica',
            name='docente_implicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='usuarios.perfildocente', verbose_name='Docente implicado'),
        ),
        migrations.AlterField(
            model_name='incidenciaacademica',
            name='fecha_incidencia',
            field=models.DateField(verbose_name='Fecha de incidencia'),
        ),
        migrations.AlterField(
            model_name='incidenciaacademica',
            name='responsable_autorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_autorizadas', to='usuarios.perfiladministrativo', verbose_name='Responsable de autorización'),
        ),
        migrations.AlterField(
            model_name='informegeneral',
            name='codigo_de_informe',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de informe'),
        ),
        migrations.AlterField(
            model_name='informegeneral',
            name='cohortes',
            field=models.ManyToManyField(blank=True, related_name='informes', to='academico.cohortedematricula', verbose_name='Cohortes de matrícula'),
        ),
        migrations.AlterField(
            model_name='informegeneral',
            name='estado_de_informe',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('Aprobado', 'Aprobado')], default='Borrador', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='informegeneral',
            name='fecha_de_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='informegeneral',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='academico.periododenivelacion', verbose_name='Periodo de nivelación registrado'),
        ),
        migrations.AlterField(
            model_name='informegeneral',
            name='tipo_de_informe',
            field=models.CharField(choices=[('Planificación', 'Planificación'), ('Avance', 'Avance'), ('Final', 'Final')], max_length=50, verbose_name='Tipo de informe'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='area_de_conocimiento',
            field=models.CharField(max_length=200, verbose_name='Área de conocimiento'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mallas_curriculares', to='academico.carrera', verbose_name='Carrera registrada'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='codigo_de_malla',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de malla curricular'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='duracion_semanas',
            field=models.IntegerField(verbose_name='Duración (en semanas)'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='estado',
            field=models.CharField(choices=[('Diseño', 'Diseño'), ('Activa', 'Activa'), ('Histórica', 'Histórica'), ('Inactiva', 'Inactiva')], default='Diseño', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='modalidad',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='total_horas_nivelacion',
            field=models.FloatField(default=0.0, verbose_name='Total de horas de nivelación'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='version_de_malla',
            field=models.CharField(max_length=20, verbose_name='Versión de malla curricular'),
        ),
        migrations.AlterField(
            model_name='matriculaparalelo',
            name='cohorte_de_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.cohortedematricula', verbose_name='Cohorte de matrícula registrada'),
        ),
        migrations.AlterField(
            model_name='matriculaparalelo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_matriculados', to='usuarios.perfilestudiante', verbose_name='Estudiante registrado'),
        ),
        migrations.AlterField(
            model_name='matriculaparalelo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='matriculaparalelo',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_matriculados', to='academico.paralelo', verbose_name='Paralelo registrado'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='capacidad_maxima',
            field=models.IntegerField(default=35, verbose_name='Número máximo de estudiantes'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='codigo_de_paralelo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de paralelo'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paralelos', to='usuarios.perfildocente', verbose_name='Docente responsable'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='jornada',
            field=models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], max_length=50, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='modalidad',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='academico.periododenivelacion', verbose_name='Periodo de nivelación registrado'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='unidad_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='academico.unidadcurricular', verbose_name='Unidad curricular'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='codigo_periodo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de periodo de nivelación'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='estado',
            field=models.CharField(choices=[('Planificación', 'Planificación'), ('En curso', 'En curso'), ('Evaluación', 'Evaluación'), ('Cerrado', 'Cerrado')], default='Planificación', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='modalidad',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='numero_periodo',
            field=models.IntegerField(verbose_name='Número de periodo de nivelación'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='periodo',
            field=models.CharField(max_length=50, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='periododenivelacion',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_de_nivelacion', to='academico.universidad', verbose_name='Universidad registrada'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='area_de_conocimiento',
            field=models.JSONField(default=list, verbose_name='Área(s) de conocimiento'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='codigo_de_unidad',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de unidad curricular'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='criterio_de_aprobacion',
            field=models.FloatField(default=7.0, verbose_name='Criterio de aprobación'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='horas_asincronicas',
            field=models.FloatField(verbose_name='Horas asincrónicas'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='horas_semanales',
            field=models.FloatField(verbose_name='Horas semanales'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='horas_sincronicas',
            field=models.FloatField(verbose_name='Horas sincrónicas'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='horas_totales',
            field=models.FloatField(verbose_name='Horas totales'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='malla_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_curriculares', to='academico.mallacurricular', verbose_name='Malla curricular registrada'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='porcentaje_minimo_asistencia',
            field=models.FloatField(default=70.0, verbose_name='Porcentaje mínimo de asistencia'),
        ),
        migrations.AlterField(
            model_name='unidadcurricular',
            name='tipo_de_componente',
            field=models.CharField(choices=[('Teórico', 'Teórico'), ('Práctico', 'Práctico'), ('Tutorial', 'Tutorial')], max_length=50, verbose_name='Tipo de componente'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='abreviatura',
            field=models.CharField(max_length=20, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='codigo_sniese',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código SNIESE'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='direccion_matriz',
            field=models.CharField(max_length=300, verbose_name='Dirección de matriz'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='identificador_visual',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Identificador visual'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la institución'),
        ),
    ]
