# Generated by Django 6.0.5 on 2026-06-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_campus_codigo_de_campus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='campo_de_conocimiento',
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.CharField(default='Por definir', max_length=200, verbose_name='Facultad'),
            preserve_default=False,
        ),
    ]
