# Generated by Django 6.0.5 on 2026-06-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_remove_carrera_campo_de_conocimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='infraestructura_compartida',
        ),
    ]
