# Generated by Django 6.0.5 on 2026-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_remove_unidadcurricular_horas_semanales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mallacurricular',
            name='area_de_conocimiento',
        ),
        migrations.RemoveField(
            model_name='mallacurricular',
            name='modalidad',
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='codigo_de_malla',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Malla curricular'),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='version_de_malla',
            field=models.CharField(max_length=20, verbose_name='Versión de Malla curricular'),
        ),
    ]
