# Generated by Django 6.0.5 on 2026-06-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_remove_mallacurricular_area_de_conocimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadcurricular',
            name='tipo_de_componente',
        ),
    ]
