# Generated by Django 5.2.15 on 2026-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_remove_unidadcurricular_tipo_de_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paralelo',
            name='codigo_de_paralelo',
            field=models.CharField(max_length=50, verbose_name='Código de paralelo'),
        ),
    ]
