# Generated by Django 6.0.5 on 2026-06-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_alter_paralelo_codigo_de_paralelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='modalidad',
        ),
    ]
