# Generated by Django 5.2.15 on 2026-06-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_remove_horario_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mallacurricular',
            name='duracion_semanas',
        ),
    ]
