# Generated by Django 5.2.15 on 2026-07-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_remove_mallacurricular_duracion_semanas'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadcurricular',
            name='horas_sincronicas_semanales',
            field=models.FloatField(default=0, verbose_name='Horas sincrónicas semanales'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tipo_de_sesion',
            field=models.CharField(choices=[('Sincrónica', 'Sincrónica'), ('Asincrónica', 'Asincrónica')], max_length=50, verbose_name='Tipo de sesión'),
        ),
    ]