# Generated by Django 5.2.15 on 2026-07-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_unidadcurricular_horas_sincronicas_semanales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='facultad',
        ),
    ]
