# Generated by Django 5.2.15 on 2026-07-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_remove_carrera_facultad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='numero_semana',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='tipo_de_sesion',
        ),
        migrations.AlterField(
            model_name='horario',
            name='espacio_de_imparticion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Espacio de impartición'),
        ),
    ]
