# Generated by Django 5.2.15 on 2026-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_remove_horario_numero_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadcurricular',
            name='area_de_conocimiento',
        ),
    ]
