# Generated by Django 5.2.15 on 2026-07-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_remove_unidadcurricular_area_de_conocimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionacademica',
            name='estado_revision',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('En revisión', 'En revisión'), ('Formalizado', 'Formalizado')], default='Borrador', max_length=50, verbose_name='Estado de revisión'),
        ),
        migrations.AddField(
            model_name='evaluacionacademica',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='academico.periododenivelacion', verbose_name='Periodo de nivelación'),
        ),
    ]
