# Generated by Django 5.2.15 on 2026-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_evaluacionacademica_estado_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='direccion_matriz',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección de matriz'),
        ),
    ]
