# Generated by Django 5.2.15 on 2026-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_alter_universidad_direccion_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia'),
        ),
    ]
