# Generated by Django 5.2.15 on 2026-07-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_alter_campus_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='modalidad',
        ),
    ]
