# Generated by Django 5.2.15 on 2026-07-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_remove_modalidad_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='periododenivelacion',
            name='numero_de_semanas',
            field=models.IntegerField(default=8, verbose_name='Número de semanas'),
        ),
    ]
