# Generated by Django 6.0.6 on 2026-06-07 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDeSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('tipo_de_identificacion', models.CharField(choices=[('Cédula', 'Cédula'), ('Pasaporte', 'Pasaporte'), ('Cédula extranjera', 'Cédula extranjera')], max_length=50)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('etnia', models.CharField(max_length=50)),
                ('porcentaje_de_discapacidad', models.FloatField(default=0.0)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=300)),
                ('estado_de_usuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario del sistema',
                'verbose_name_plural': 'Usuarios del sistema',
            },
        ),
        migrations.CreateModel(
            name='PerfilAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_administrativo', models.CharField(max_length=50, unique=True)),
                ('perfil_administrativo', models.CharField(choices=[('Rector', 'Rector'), ('Vicerrector académico', 'Vicerrector académico'), ('Director de dirección de admisión y nivelación', 'Director de dirección de admisión y nivelación'), ('Coordinador de dirección de admisión y nivelación ', 'Coordinador de dirección de admisión y nivelación '), ('Coordinador de unidad académica', 'Coordinador de unidad académica')], max_length=100)),
                ('identificador_coordinador_dan', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('identificador_coordinador_ua', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unidad_academica', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_de_sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrative', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil administrativo',
                'verbose_name_plural': 'Perfiles administrativos',
            },
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_institucional', models.CharField(max_length=50, unique=True)),
                ('tipo_de_vinculacion', models.CharField(choices=[('Nombramiento', 'Nombramiento'), ('Contrato', 'Contrato'), ('Ocasional', 'Ocasional'), ('Honorario', 'Honorario')], max_length=50)),
                ('tiempo_de_dedicacion', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Tiempo parcial', 'Tiempo parcial')], max_length=50)),
                ('estado_de_vinculacion', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Licencia temporal', 'Licencia temporal')], default='Activo', max_length=50)),
                ('carga_horaria_maxima', models.FloatField(default=40.0)),
                ('carga_horaria_actual', models.FloatField(default=0.0)),
                ('especialidades', models.JSONField(default=list)),
                ('usuario_de_sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil docente',
                'verbose_name_plural': 'Perfiles docentes',
            },
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_institucional', models.CharField(max_length=50, unique=True)),
                ('numero_de_matricula', models.CharField(max_length=50, unique=True)),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], max_length=50)),
                ('registro_de_cupo', models.CharField(choices=[('Registro regular', 'Registro regular'), ('Segunda matrícula', 'Segunda matrícula'), ('Proceso de exoneración', 'Proceso de exoneración')], max_length=50)),
                ('estado_de_matricula', models.CharField(choices=[('Aspirante', 'Aspirante'), ('Pendiente de pago', 'Pendiente de pago'), ('Matriculado', 'Matriculado'), ('Retirado', 'Retirado'), ('Anulada', 'Anulada')], default='Aspirante', max_length=50)),
                ('campus_registrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academico.campus')),
                ('carrera_registrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academico.carrera')),
                ('usuario_de_sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil estudiante',
                'verbose_name_plural': 'Perfiles estudiantes',
            },
        ),
    ]
