# Generated by Django 6.0.5 on 2026-06-09 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='identificador_administrativo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de identificador administrativo'),
        ),
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='identificador_coordinador_dan',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de identificador DAN'),
        ),
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='identificador_coordinador_ua',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de identificador UA'),
        ),
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='perfil_administrativo',
            field=models.CharField(choices=[('Rector', 'Rector'), ('Vicerrector académico', 'Vicerrector académico'), ('Director de dirección de admisión y nivelación', 'Director de dirección de admisión y nivelación'), ('Coordinador de dirección de admisión y nivelación ', 'Coordinador de dirección de admisión y nivelación '), ('Coordinador de unidad académica', 'Coordinador de unidad académica')], max_length=100, verbose_name='Perfil administrativo'),
        ),
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='unidad_academica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad académica'),
        ),
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='usuario_de_sistema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de sistema registrado'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='carga_horaria_actual',
            field=models.FloatField(default=0.0, verbose_name='Carga horaria actual (en horas)'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='carga_horaria_maxima',
            field=models.FloatField(default=40.0, verbose_name='Carga horaria máxima (en horas)'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='especialidades',
            field=models.JSONField(default=list, verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='estado_de_vinculacion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Licencia temporal', 'Licencia temporal')], default='Activo', max_length=50, verbose_name='Estado de vinculación'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='identificador_institucional',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de identificador institucional'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='tiempo_de_dedicacion',
            field=models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Tiempo parcial', 'Tiempo parcial')], max_length=50, verbose_name='Tiempo de dedicación'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='tipo_de_vinculacion',
            field=models.CharField(choices=[('Nombramiento', 'Nombramiento'), ('Contrato', 'Contrato'), ('Ocasional', 'Ocasional'), ('Honorario', 'Honorario')], max_length=50, verbose_name='Tipo de vinculación'),
        ),
        migrations.AlterField(
            model_name='perfildocente',
            name='usuario_de_sistema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de sistema registrado'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='estado_de_matricula',
            field=models.CharField(choices=[('Aspirante', 'Aspirante'), ('Pendiente de pago', 'Pendiente de pago'), ('Matriculado', 'Matriculado'), ('Retirado', 'Retirado'), ('Anulada', 'Anulada')], default='Aspirante', max_length=50, verbose_name='Estado de matrícula'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='identificador_institucional',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de identificador institucional'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='jornada',
            field=models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], max_length=50, verbose_name='Jornada registrada'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='numero_de_matricula',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de matrícula'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='registro_de_cupo',
            field=models.CharField(choices=[('Registro regular', 'Registro regular'), ('Segunda matrícula', 'Segunda matrícula'), ('Proceso de exoneración', 'Proceso de exoneración')], max_length=50, verbose_name='Registro de cupo'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='usuario_de_sistema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de sistema registrado'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='correo_institucional',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo institucional'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='direccion',
            field=models.CharField(max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='estado_de_usuario',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50, verbose_name='Estado de usuario'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='etnia',
            field=models.CharField(max_length=50, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='nombres',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='porcentaje_de_discapacidad',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de discapacidad'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='sexo',
            field=models.CharField(max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='tipo_de_identificacion',
            field=models.CharField(choices=[('Cédula', 'Cédula'), ('Pasaporte', 'Pasaporte'), ('Cédula extranjera', 'Cédula extranjera')], max_length=50, verbose_name='Tipo de identificación'),
        ),
    ]
