# Generated by Django 6.0.5 on 2026-06-13 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_campus_codigo_de_campus_and_more'),
        ('usuarios', '0002_alter_perfiladministrativo_identificador_administrativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiladministrativo',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrativos', to='academico.universidad', verbose_name='Universidad registrada'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='estado_de_matricula',
            field=models.CharField(choices=[('Aspirante', 'Aspirante'), ('Pendiente de pago', 'Pendiente de pago'), ('Matriculado', 'Matriculado'), ('Retirada', 'Retirada'), ('Anulada', 'Anulada')], default='Aspirante', max_length=50, verbose_name='Estado de matrícula'),
        ),
    ]
