# Generated by Django 6.0.5 on 2026-06-13 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_campus_codigo_de_campus_and_more'),
        ('usuarios', '0003_perfiladministrativo_universidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrativos', to='academico.universidad', verbose_name='Universidad registrada'),
        ),
    ]
