# Generated by Django 6.0.5 on 2026-06-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfiladministrativo_universidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodesistema',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='etnia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='porcentaje_de_discapacidad',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Porcentaje de discapacidad'),
        ),
        migrations.AlterField(
            model_name='usuariodesistema',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo'),
        ),
    ]
