# Generated by Django 6.0.5 on 2026-06-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuariodesistema_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladministrativo',
            name='perfil_administrativo',
            field=models.CharField(choices=[('Rector', 'Rector'), ('Vicerrector académico', 'Vicerrector académico'), ('Director de dirección de admisión y nivelación', 'Director de dirección de admisión y nivelación'), ('Coordinador de dirección de admisión y nivelación', 'Coordinador de dirección de admisión y nivelación'), ('Coordinador de unidad académica', 'Coordinador de unidad académica')], max_length=100, verbose_name='Perfil administrativo'),
        ),
    ]
