# Generated by Django 6.0.5 on 2026-06-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfiladministrativo_perfil_administrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='estado_de_matricula',
            field=models.CharField(choices=[('Matriculado', 'Matriculado'), ('Retirado', 'Retirado'), ('Anulado', 'Anulado')], default='Matriculado', max_length=50, verbose_name='Estado de matrícula'),
        ),
    ]
