# Generated by Django 6.0.5 on 2026-06-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_remove_campus_infraestructura_compartida'),
        ('usuarios', '0007_alter_perfilestudiante_estado_de_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='academico.universidad', verbose_name='Universidad registrada'),
        ),
    ]
