# Generated by Django 6.0.5 on 2026-06-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_remove_unidadcurricular_tipo_de_componente'),
        ('usuarios', '0008_perfildocente_universidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_de_periodo', to='academico.periododenivelacion', verbose_name='Periodo de nivelación'),
        ),
    ]
