# Generated by Django 6.0.5 on 2026-06-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfilestudiante_periodo_de_nivelacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfildocente',
            name='carga_horaria_actual',
        ),
    ]
