# Generated by Django 5.2.15 on 2026-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_perfildocente_carga_horaria_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildocente',
            name='carga_horaria_maxima',
            field=models.FloatField(default=20.0, verbose_name='Carga horaria máxima (en horas)'),
        ),
    ]
