# Generated by Django 5.2.15 on 2026-07-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_remove_carrera_facultad'),
        ('usuarios', '0011_perfildocente_jornadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiladministrativo',
            name='carrera_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinadores_ua', to='academico.carrera', verbose_name='Carrera asignada'),
        ),
    ]
