# Generated by Django 5.2.15 on 2026-07-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_perfiladministrativo_carrera_asignada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfildocente',
            name='especialidades',
        ),
    ]
